1. import the numbers.csv

In [2]:
import numpy as np

In [3]:
data = np.genfromtxt('numbers.csv', delimiter=',', names=True)
data = data.astype('float64')
data


array([101., 102., 103., 104., 105., 106., 107., 108., 109., 110., 111.,
       112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
       123., 124., 125., 126., 127., 128., 129., 130., 131., 132., 133.,
       134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
       145., 146., 147., 148.])

2. multiply 45 by the array

In [4]:
data * 45

array([4545., 4590., 4635., 4680., 4725., 4770., 4815., 4860., 4905.,
       4950., 4995., 5040., 5085., 5130., 5175., 5220., 5265., 5310.,
       5355., 5400., 5445., 5490., 5535., 5580., 5625., 5670., 5715.,
       5760., 5805., 5850., 5895., 5940., 5985., 6030., 6075., 6120.,
       6165., 6210., 6255., 6300., 6345., 6390., 6435., 6480., 6525.,
       6570., 6615., 6660.])

3. divide the array by 67.7

In [5]:
data / 67.7

array([1.49187592, 1.50664697, 1.52141802, 1.53618907, 1.55096012,
       1.56573117, 1.58050222, 1.59527326, 1.61004431, 1.62481536,
       1.63958641, 1.65435746, 1.66912851, 1.68389956, 1.69867061,
       1.71344165, 1.7282127 , 1.74298375, 1.7577548 , 1.77252585,
       1.7872969 , 1.80206795, 1.816839  , 1.83161004, 1.84638109,
       1.86115214, 1.87592319, 1.89069424, 1.90546529, 1.92023634,
       1.93500739, 1.94977843, 1.96454948, 1.97932053, 1.99409158,
       2.00886263, 2.02363368, 2.03840473, 2.05317578, 2.06794682,
       2.08271787, 2.09748892, 2.11225997, 2.12703102, 2.14180207,
       2.15657312, 2.17134417, 2.18611521])

4. raise the array to the power of 5

In [7]:
list_1 = [1,2,3]
array_1 = np.array(list_1)
print("array_1 raised to the power of array_1: ",array_1**array_1)

array_1 raised to the power of array_1:  [ 1  4 27]
