1. Load the numbers2.csv file and convert it into a two-dimensional NumPy array

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("../datasets/numbers2.csv",header=None) 
list_2D = df.values
mat1 = np.array(list_2D) 

print("Type/Class of this object:",type(mat1)) 

print("Here is the matrix\n----------\n",mat1,"\n----------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


2. Tuples can be converted into multi-dimensional arrays

In [2]:
tuple_2D = np.array([(1.5,2,3), (4,5,6)]) 

mat_tuple = np.array(tuple_2D) 

print (mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
