In [1]:
import numpy as np
matrix_1 = np.random.randint(1,10,9).reshape(3,3)
matrix_2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",matrix_1)
print("\n2nd Matrix of random single-digit numbers\n",matrix_2)



1st Matrix of random single-digit numbers
 [[9 5 2]
 [8 8 2]
 [2 6 7]]

2nd Matrix of random single-digit numbers
 [[9 7 2]
 [8 2 9]
 [5 1 8]]


In [2]:
print("\nAddition\n", matrix_1+matrix_2)
print("\nMultiplication\n", matrix_1*matrix_2)
print("\nDivision\n", matrix_1/matrix_2)
print("\nLinear combination: 3*A - 2*B\n", 3*matrix_1-2*matrix_2)



Addition
 [[18 12  4]
 [16 10 11]
 [ 7  7 15]]

Multiplication
 [[81 35  4]
 [64 16 18]
 [10  6 56]]

Division
 [[1.         0.71428571 1.        ]
 [1.         4.         0.22222222]
 [0.4        6.         0.875     ]]

Linear combination: 3*A - 2*B
 [[  9   1   2]
 [  8  20 -12]
 [ -4  16   5]]


In [3]:
print("\nAddition of a scalar (100)\n", 100+matrix_1)

print("\nExponentiation, matrix cubed here\n", matrix_1**3)
print("\nExponentiation, square root using 'pow' function\n",pow(matrix_1,0.5))



Addition of a scalar (100)
 [[109 105 102]
 [108 108 102]
 [102 106 107]]

Exponentiation, matrix cubed here
 [[729 125   8]
 [512 512   8]
 [  8 216 343]]

Exponentiation, square root using 'pow' function
 [[3.         2.23606798 1.41421356]
 [2.82842712 2.82842712 1.41421356]
 [1.41421356 2.44948974 2.64575131]]
