1. Create an array of 10 elements and examine its various elements by slicing and indexing the array with slightly different syntaxes.

In [2]:
import numpy as np
array_1 = np.arange(0,11) 

print("Array:",array_1) 

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


2. Print the element in the seventh position

In [3]:
print("Element at 7th index is:", array_1[7]) 

Element at 7th index is: 7


3. Print the elements between the third and sixth positions

In [4]:
print("Elements from 3rd to 5th index are:", array_1[3:6]) 

Elements from 3rd to 5th index are: [3 4 5]


4. Print the elements until the fourth position

In [5]:
print("Elements up to 4th index are:", array_1[:4]) 

Elements up to 4th index are: [0 1 2 3]


5. Print the elements backwards

In [7]:
print("Elements from last backwards are:", array_1[-1::-1]) 

Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]


6. Print the elements using their backward index

In [9]:
print("3 Elements from last backwards are:", array_1[-1:-6:-2]) 

3 Elements from last backwards are: [10  8  6]


7.  Create a new array called array_2

In [11]:
array_2 = np.arange(0,21,2) 

print("New array:",array_2)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


8. Print the second, fourth, and ninth elements

In [13]:
print("Elements at 2nd, 4th, and 9th index are:", array_2[[2,4,9]]) 

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


9. Create a multi-dimensional array

In [14]:
matrix_1 = np.random.randint(10,100,15).reshape(3,5) 

print("Matrix of random 2-digit numbers\n ",matrix_1) 

Matrix of random 2-digit numbers
  [[17 20 78 79 10]
 [44 62 41 40 71]
 [19 47 84 79 63]]


10. Access the values using double bracket indexing

In [15]:
print("\nDouble bracket indexing\n") 

print("Element in row index 1 and column index 2:", matrix_1[1][2]) 


Double bracket indexing

Element in row index 1 and column index 2: 41


11. Access the values using single bracket indexing

In [17]:
print("\nSingle bracket with comma indexing\n") 

print("Element in row index 1 and column index 2:", matrix_1[1,2]) 


Single bracket with comma indexing

Element in row index 1 and column index 2: 41


12. Access the values in a multi-dimensional array using a row or column 

In [18]:
print("\nRow or column extract\n") 

print("Entire row at index 2:", matrix_1[2]) 

print("Entire column at index 3:", matrix_1[:,3]) 


Row or column extract

Entire row at index 2: [19 47 84 79 63]
Entire column at index 3: [79 40 79]


13. Print the matrix with the specified row and column indices 

In [19]:
print("\nSubsetting sub-matrices\n") 

print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", matrix_1[1:3,3:5])


Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[40 71]
 [79 63]]


14. Print the matrix with the specified row and column indices

In [20]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", matrix_1[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[20 79]
 [62 40]]
