In [1]:
import numpy as np
print("Vector of zeros: ",np.zeros(5))


Vector of zeros:  [0. 0. 0. 0. 0.]


In [2]:
print("Matrix of zeros: ",np.zeros((3,4)))

Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
print("Matrix of 5's: ",5*np.ones((3,3)))

Matrix of 5's:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [4]:
print("Identity matrix of dimension 2:",np.eye(2))

Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]


In [5]:
print("Identity matrix of dimension 4:",np.eye(4))

Identity matrix of dimension 4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))

Random matrix of shape (4,3):
 [[7 8 1]
 [8 1 2]
 [2 6 5]
 [1 1 2]]
